### ISSUE TITLE
Upload companies list - MASTER copy

### ISSUE THREAD

**Issue by sstepanik** [elmo/valtari#128]
https://drive.google.com/open?id=0B7jU0xNEpe7NR1RiV1pPX3hPbWc

This list contains approx 103,000 companies, with columns aligned according to the original businesses.csv file. 

I have adjusted all revenues and employee count numbers — segmenting them into 14 bands and extrapolating growth. 

The list is now ready to be uploaded onto the platform. What still needs to occur is normalization of titles, i.e., ensure no companies are in all caps. remove all organization suffixes (inc., llc, etc...). Additionally, you will notice that for companies greater than $20MM the addresses and phone numbers are not spread across the columns. If we can not automate this then it will be another project for Ukrainians.

**Comment by elmo** [comment]
What I need to a  a two column list of what needs to be converted to what:

example:

Inc :  Inc.,
Mister, :Mr.

etc.

Could one of you put put that together?
