### ISSUE TITLE
Send logged out user to home view

### ISSUE THREAD

**Issue by ptgrimm** [elmo/valtari#13]
linkedin authenticated session dies after x period of time. just need to send user to home/logged out page so they don't see this screen:

**Comment by ptgrimm** [comment]
if you return the tab after a while, you're logged out and get this

**Comment by ptgrimm** [comment]
<img width="976" alt="screen shot 2016-09-26 at 11 56 40 am" src="https://cloud.githubusercontent.com/assets/3527153/18847877/c64b9c8c-83e0-11e6-8c56-1ffb917027ea.png">

**Comment by elmo** [comment]
I believe this is already the case. Please verify.
