### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by ptgrimm** [elmo/valtari#132]
We want the ability for an admin to create events with, at least, these attributes (see image)   question is an end time/date necessary?

**Comment by ptgrimm** [comment]
![screen shot 2017-01-13 at 12 57 17 pm](https://cloud.githubusercontent.com/assets/3527153/21945422/0ce322e6-d990-11e6-80e2-197e2fcf2e10.png)

**Comment by ptgrimm** [comment]
HTML code ready to use: https://codepen.io/anon/pen/rjYzrb

**Comment by elmo** [comment]
The basics are there.  Just saw the mockup.  I'll add those elements later.

**Comment by elmo** [comment]
I've added the image upload piece.
