### ISSUE TITLE
Signed in flash message doesn't go away, says google

### ISSUE THREAD

**Issue by ptgrimm** [elmo/valtari#24]

**Comment by ptgrimm** [comment]
Needs to disappear after 5 seconds. Seems to say you authenticated with Google no matter what.  Take out who provided the authentication, or make it accurate.

**Comment by elmo** [comment]
I've made the flash message accurate now.  I think we need to incorporate it somewhere in our design.  

The template holding the flash messages is:

app/views/shared/_flash.html.erb
