### ISSUE TITLE
Need list of options for Geography

### ISSUE THREAD

**Issue by elmo** [elmo/valtari#38]
@sstepanik @ptgrimm Are we going to be international out of the gate.  If so, we need is list of regions / countries where we are going to operate.

**Comment by sstepanik** [comment]
Here is a link to our "geography tree": https://drive.google.com/open?id=0B7jU0xNEpe7NZzhWSE5mcmU5eTg

**Comment by elmo** [comment]
I've installed the GEO tree on the development server:

see: https://valtari.herokuapp.com/admin/geos

I still need to apply the log of marking our various entities as belonging to the appropriate geo.
