### ISSUE TITLE
Need list of options for company types

### ISSUE THREAD

**Issue by elmo** [elmo/valtari#39]

**Comment by sstepanik** [comment]
Capital Providers;
- Private Equity Group
- Family Office
- Senior Lender
- Junior Capital Provider
- Individual Accredited Investor
- Venture Capital
- Search Fund
- Independent Sponsor 
- Hedge Fund
- Holding Company

Advisor:
- Merchant Bank
- Investor Bank
- M&A Advisory Firm
- Business Broker
- Consultant
- Law Firm
- Accountant

Company Owners & Strategics:
- Corporation
