### ISSUE TITLE
Buy Side Mandate requirements

### ISSUE THREAD

**Issue by tschann** [elmo/valtari#46]
This user action will ask for
1) Title: text input
2) Revenue: e.g. $55.55m (5,550,000) including negative numbers
3) Geography: Select
4) EBITDA: Same as Revenue
5) Industries: 10 major groups, with industries inside
6) Company Stage: text input

**Comment by elmo** [comment]
This ticket has no information, ideally tickets should have at least one action item.

**Comment by ptgrimm** [comment]
Revenue select could look like this: https://jsfiddle.net/6vskdgmv/

**Comment by tschann** [comment]
here's a mockup 
<img width="510" alt="screen shot 2017-03-05 at 10 56 09 am" src="https://cloud.githubusercontent.com/assets/3527153/23590331/6eec40d8-0192-11e7-9fd3-adcd3584c9ba.png">
