### ISSUE TITLE
List of 100 Organizations

### ISSUE THREAD

**Issue by sstepanik** [elmo/valtari#62]
Per our conversation tonight, I took the first 100 firms from our Private Equity list and put them into a .csv file. We need to sanitize the legal company name suffix and any respective formatting, as well as remove any all caps formatting of names. 
https://drive.google.com/open?id=0B7jU0xNEpe7NSVplT2U4aTJNcjg

**Comment by elmo** [comment]
I've created the basic admin infrastructure for entering organizations.

We still need to define the list of attributes for organizations.

**Comment by elmo** [comment]
I'll close this ticket and open a new one with further requirements.
